spring:
  profiles: default
server:
  port: 8080
db:
  name: {{cookiecutter.system_code}}db
  url: "http://localhost:5984"

---
spring:
  profiles: development

server:
  port: 8080
db:
  name: {{cookiecutter.system_code}}db
  url: "http://db:5984"
